name: Publish Package

on:
  release:
    types: [published]

env:
  MINIMUM_PYTHON_VERSION: '3.10'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build-for-pypi:
      needs: ci
      runs-on: ubuntu-latest
      permissions:
        contents: read
      steps:
        - uses: actions/checkout@v4
        - name: Install Python ${{ env.MINIMUM_PYTHON_VERSION }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.MINIMUM_PYTHON_VERSION }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install uv
        - name: Build the package
          run: uv build
        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v4
          with:
            name: python-dist
            path: dist/
            if-no-files-found: error
            retention-days: 1

  deploy-to-pypi:
      # IMPORTANT: use a seperate job for this as each step has access to the tokens
      needs: build-for-pypi
      runs-on: ubuntu-latest
      environment: pypi
      permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
        id-token: write
      steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist
      - name: Publish package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
